### ISSUE TITLE
Support configuring session recording locally in SSSD 

### ISSUE THREAD

**Issue by spbnick** [Scribery/meta#1]

**Comment by spbnick** [comment]
First step: get changes merged into SSSD.

**Comment by spbnick** [comment]
Test comment.

**Comment by spbnick** [comment]
The following rough plan was drawn after discussion with @pbrezina.

Essentially, we'll be introducing another user attribute to sysdb:
"sessionRecording".

If selective session recording is enabled in sssd.conf (i.e.
"session_recording/scope = some" and users/groups to record are specified),
and this attribute is present and set to TRUE, then session recording for that
user is enabled and NSS responder substitutes "/usr/bin/tlog-rec" as the user
shell, when filling in the response. The PAM responder, in its turn, will add
environment variable specifying the actual user shell to tlog-rec (e.g.
TLOG_REC_SHELL=/bin/bash).

To implement that we'll need to move the code which reads various shell
configuration options, and figures out the final user shell, from the NSS
responder to the common responder code, so that both NSS and PAM responders
could use it.

We will be adding that attribute to both the retrieved result and the entry in
sysdb after we receive the result in "cache_req_done". This is a bit ugly and
Pavel has the idea of moving that logic to the provider eventually (IIRC), but
we'll start with this. Once we get the user result, the logic goes like this:

    If selective session recording is enabled
        If user name matches any of the configured user names
            Set sessionRecording attribute to TRUE
        else, if user's initgroups data expired (SYSDB_INITGR_EXPIRE elapsed)
            Get initgroups data for the user (call cache_req_initgroups_by_name)
            If any user group matches any of the configured recorded group names
                Set sessionRecording attribute to TRUE
            Else
                Set sessionRecording attribute to FALSE

Before matching the user name and the group names in the user entry against
the user names and group names in configuration, we'll pass them through
nss_get_name_from_msg and then through sss_output_name, so that they look
exactly what the admin will see in "getent passwd" and "getent group" output.

However, a difficulty was encountered regarding making this plan work with
midpoint cache update. Basically, midpoint cache update is done out-of-band,
bypassing "cache_req_done". This way an update to initgroups data can go
unnoticed by the logic above, and the sessionRecording attribute would not be
updated. Handling that case would require more hacky solutions.

For now we (mostly @pbrezina) are trying to see what can be done on the data
provider side, as that seems a better place to do things.

**Comment by pbrezina** [comment]
Hi, to solve the issue with midpoint searches I propose this:

1. Leverage `dp_req_initgr_pp()` (`pp` stands for `postprocess`). This function is called after a data provider `initgroups` request is finished (user's groups are refreshed) and before the data provider returns a reply to the responder and thus finishing the `cache_req` request. At this moment, this function is used to notify the `NSS` responder that initgroups may have changed and thus the responder invalidates in-memory cache. Please move current contents of the function into separate function. So the codo flow will be:
```c
1. responder: cache_req issues a DP request
2. provider: dp initgroups request starts
3. provider: initgroups are finished
4. provider: dp_req_initgr_pp()
    - notify NSS responder
    - match session recording settings
        - username is stored in struct dp_initgr_ctx
        - sysdb_initgroups() will give you current groups list (the one stored in dp_initgr_ctx is the old 
group list)
        - update the user object with session_recording flag
5. provider: send reply to responder and finish dp request
6. responder: cache_req initgroups is finished
```

I suggest you to create a new structure that will hold the session recording information, lets say `struct be_session_recording_ctx` and place it inside `struct be_ctx` together with failover and dns resolver contexts. You can access it later through `struct data_provider -> be`. Options can be loaded in `be_process_init()`.

If possible, put all session recording code into separate module.

**Comment by spbnick** [comment]
Thank you, @pbrezina, I'll look into implementing your solution!

**Comment by spbnick** [comment]
A draft of the implemented plan is submitted for comments in SSSD/sssd#136.
@pbrezina, I'd be grateful, if you could take a look at it and provide some guidance.

**Comment by spbnick** [comment]
A full working implementation, including both NSS and PAM parts, is available for review at SSSD/sssd#136.

**Comment by spbnick** [comment]
The patch set passed review and is ready to be merged, but is held until about end of June to prevent unnecessary rebasing work with patches to be backported in the pipeline.

**Comment by spbnick** [comment]
The patch set is finally merged.
